sudo: false
language: erlang
otp_release:  # travisci complains 17.1 of a 'filelib bug', so excluded
       - 18.0
       - 17.5
       - 17.4
       - 17.3
       - 17.0
cache:
  directories:
  - $HOME/.cache/rebar3/hex/default/
install: "true" # don't let travis run get-deps
script: "make && make test"

after_success: "make dialyzer"

branches:
        only:
                - master
notifications:
  email:
    - example@example.com

